repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.6
    hooks:
      - id: ruff
        args: ["--fix", "--select", "E,F,W", "--ignore", "E501,E701,E702,E402"]
      - id: ruff-format
