# -*- coding: utf-8 -*-
"""
CANONICAL BRAND TIERS — single source of truth for JA Uniforms (2026-04-24)

This module is THE authoritative mapping of brand -> tier for the entire
application. `scorer.py` and `lead_data_enrichment.py` both import from
here to build their tier knowledge. No other file should hardcode tier
assignments.

TIER SYSTEM (JA uses 4 active sales tiers + 1 skip tier; all active tiers
are 4-star and above):

  tier1_ultra_luxury    Top of STR Luxury (ADR $500-3,000+)
  tier2_luxury          Rest of STR Luxury (ADR $300-500)
  tier3_upper_upscale   STR Upper Upscale (ADR $200-350)
  tier4_upscale         STR Upscale (ADR $140-200)
  tier5_skip            Upper Midscale / Midscale / Economy (NOT targeted)

SOURCES
  STR 2024 January Chain Scales (CoStar)
  STR 2023 Chain Scales (NCREIF + McKinney TX gov attachment)
  STR 2016 North America & Caribbean list (SlideShare archive)
  CBRE/MMCG Hospitality Market Report April 2026
  Pursuitist Top 10 Luxury Brands 2025
  HSMAI / Forbes Travel Guide / AAA Diamond Rating
"""

from collections import Counter
from typing import Optional


CANONICAL_TIERS: dict[str, str] = {
    # ============ TIER 1 ULTRA LUXURY ============
    # — Elite global chains
    "aman": "tier1_ultra_luxury",
    "amangiri": "tier1_ultra_luxury",
    "amanera": "tier1_ultra_luxury",
    "amanyara": "tier1_ultra_luxury",
    "four seasons": "tier1_ultra_luxury",
    "ritz-carlton": "tier1_ultra_luxury",
    "ritz carlton": "tier1_ultra_luxury",
    "the ritz-carlton": "tier1_ultra_luxury",
    "ritz-carlton reserve": "tier1_ultra_luxury",
    "rosewood": "tier1_ultra_luxury",
    "mandarin oriental": "tier1_ultra_luxury",
    "peninsula": "tier1_ultra_luxury",
    "the peninsula": "tier1_ultra_luxury",
    "st. regis": "tier1_ultra_luxury",
    "st regis": "tier1_ultra_luxury",
    "waldorf astoria": "tier1_ultra_luxury",
    "waldorf-astoria": "tier1_ultra_luxury",
    "park hyatt": "tier1_ultra_luxury",
    "montage": "tier1_ultra_luxury",
    "belmond": "tier1_ultra_luxury",
    "bulgari": "tier1_ultra_luxury",
    "bvlgari": "tier1_ultra_luxury",
    "armani hotel": "tier1_ultra_luxury",
    "baccarat hotel": "tier1_ultra_luxury",
    "cheval blanc": "tier1_ultra_luxury",
    "dorchester collection": "tier1_ultra_luxury",
    "oetker collection": "tier1_ultra_luxury",
    "rocco forte": "tier1_ultra_luxury",
    "capella": "tier1_ultra_luxury",
    "raffles": "tier1_ultra_luxury",
    "six senses": "tier1_ultra_luxury",
    "como hotels": "tier1_ultra_luxury",
    "como shambhala": "tier1_ultra_luxury",
    "kempinski": "tier1_ultra_luxury",
    "corinthia": "tier1_ultra_luxury",
    "lxr hotels": "tier1_ultra_luxury",
    "lxr": "tier1_ultra_luxury",
    "auberge": "tier1_ultra_luxury",
    "auberge collection": "tier1_ultra_luxury",
    "auberge resorts collection": "tier1_ultra_luxury",
    "faena": "tier1_ultra_luxury",
    "one & only": "tier1_ultra_luxury",
    "one&only": "tier1_ultra_luxury",
    "one and only": "tier1_ultra_luxury",
    "oneandonly": "tier1_ultra_luxury",
    "oberoi": "tier1_ultra_luxury",
    "taj": "tier1_ultra_luxury",
    "shangri-la": "tier1_ultra_luxury",
    "preferred hotels": "tier1_ultra_luxury",
    "leading hotels of the world": "tier1_ultra_luxury",
    "the leading hotels": "tier1_ultra_luxury",
    "small luxury hotels": "tier1_ultra_luxury",
    "soneva": "tier1_ultra_luxury",
    "nihi": "tier1_ultra_luxury",
    "zannier": "tier1_ultra_luxury",
    "patina hotels": "tier1_ultra_luxury",
    "patina maldives": "tier1_ultra_luxury",
    "palazzo versace": "tier1_ultra_luxury",
    "the brando": "tier1_ultra_luxury",
    "single thread": "tier1_ultra_luxury",
    "singlethread": "tier1_ultra_luxury",
    "eden rock": "tier1_ultra_luxury",
    "jade mountain": "tier1_ultra_luxury",
    # — Caribbean ultra-luxury independents
    "dorado beach": "tier1_ultra_luxury",
    "cap juluca": "tier1_ultra_luxury",
    "sandy lane": "tier1_ultra_luxury",
    "parrot cay": "tier1_ultra_luxury",
    "necker island": "tier1_ultra_luxury",
    "peter island": "tier1_ultra_luxury",
    "oil nut bay": "tier1_ultra_luxury",
    "jumby bay": "tier1_ultra_luxury",
    "secret bay": "tier1_ultra_luxury",
    "curtain bluff": "tier1_ultra_luxury",
    "half moon": "tier1_ultra_luxury",
    "round hill": "tier1_ultra_luxury",
    "tryall club": "tier1_ultra_luxury",
    "hermitage bay": "tier1_ultra_luxury",
    "carlisle bay": "tier1_ultra_luxury",
    "sugar beach viceroy": "tier1_ultra_luxury",
    "ladera resort": "tier1_ultra_luxury",
    "belle mont farm": "tier1_ultra_luxury",
    "ambergris cay": "tier1_ultra_luxury",
    "grace bay club": "tier1_ultra_luxury",
    "the palms turks": "tier1_ultra_luxury",
    "casa de campo": "tier1_ultra_luxury",
    "kamalame cay": "tier1_ultra_luxury",
    "musha cay": "tier1_ultra_luxury",
    "baha mar": "tier1_ultra_luxury",
    "baker's bay": "tier1_ultra_luxury",
    "rosewood baha mar": "tier1_ultra_luxury",
    "albany bahamas": "tier1_ultra_luxury",
    "the cove atlantis": "tier1_ultra_luxury",
    "the loren": "tier1_ultra_luxury",
    "hamilton princess": "tier1_ultra_luxury",
    "tucker's point": "tier1_ultra_luxury",
    "sanctuary cap cana": "tier1_ultra_luxury",
    "zemi beach": "tier1_ultra_luxury",
    "zemi": "tier1_ultra_luxury",
    # — US ultra-luxury independents
    "acqualina": "tier1_ultra_luxury",
    "the setai": "tier1_ultra_luxury",
    "the carlyle": "tier1_ultra_luxury",
    "the mark hotel": "tier1_ultra_luxury",
    "the plaza hotel": "tier1_ultra_luxury",
    "hotel bel-air": "tier1_ultra_luxury",
    "the breakers": "tier1_ultra_luxury",
    "breakers palm beach": "tier1_ultra_luxury",
    "little palm island": "tier1_ultra_luxury",
    "the cloister": "tier1_ultra_luxury",
    "sea island": "tier1_ultra_luxury",
    "blackberry farm": "tier1_ultra_luxury",
    "blackberry mountain": "tier1_ultra_luxury",
    "triple creek ranch": "tier1_ultra_luxury",
    "the resort at pelican hill": "tier1_ultra_luxury",
    "pelican hill": "tier1_ultra_luxury",
    "the biltmore": "tier1_ultra_luxury",
    "the broadmoor": "tier1_ultra_luxury",
    "the surf club": "tier1_ultra_luxury",
    "greenbrier": "tier1_ultra_luxury",
    "nemacolin": "tier1_ultra_luxury",
    "newbury boston": "tier1_ultra_luxury",
    "grand wailea": "tier1_ultra_luxury",
    "fontainebleau": "tier1_ultra_luxury",
    "boca raton resort": "tier1_ultra_luxury",
    "equinox hotel": "tier1_ultra_luxury",
    "canyon ranch": "tier1_ultra_luxury",
    "wynn": "tier1_ultra_luxury",
    "mr. c": "tier1_ultra_luxury",
    "vidanta": "tier1_ultra_luxury",
    "montage palmetto bluff": "tier1_ultra_luxury",
    "montage laguna beach": "tier1_ultra_luxury",
    "montage deer valley": "tier1_ultra_luxury",
    "montage kapalua bay": "tier1_ultra_luxury",
    "montage los cabos": "tier1_ultra_luxury",
    "montage big sky": "tier1_ultra_luxury",
    "montage healdsburg": "tier1_ultra_luxury",
    # ============ TIER 2 LUXURY ============
    "jw marriott": "tier2_luxury",
    "w hotels": "tier2_luxury",
    "w hotel": "tier2_luxury",
    "edition": "tier2_luxury",
    "conrad": "tier2_luxury",
    "fairmont": "tier2_luxury",
    "sofitel": "tier2_luxury",
    "sofitel legend": "tier2_luxury",
    "intercontinental": "tier2_luxury",
    "grand hyatt": "tier2_luxury",
    "andaz": "tier2_luxury",
    "alila": "tier2_luxury",
    "thompson": "tier2_luxury",
    "thompson hotels": "tier2_luxury",
    "langham": "tier2_luxury",
    "viceroy": "tier2_luxury",
    "1 hotels": "tier2_luxury",
    "1hotel": "tier2_luxury",
    "1 hotel": "tier2_luxury",
    "nobu hotel": "tier2_luxury",
    "miraval": "tier2_luxury",
    "pendry": "tier2_luxury",
    "sls": "tier2_luxury",
    "mondrian": "tier2_luxury",
    "delano": "tier2_luxury",
    "banyan tree": "tier2_luxury",
    "signia by hilton": "tier2_luxury",
    "signia": "tier2_luxury",
    "the luxury collection": "tier2_luxury",
    "luxury collection": "tier2_luxury",
    "design hotels": "tier2_luxury",
    "hualuxe": "tier2_luxury",
    "vignette collection": "tier2_luxury",
    "virgin hotels": "tier2_luxury",
    "unbound collection": "tier2_luxury",
    "the unbound collection by hyatt": "tier2_luxury",
    "proper hotel": "tier2_luxury",
    "proper": "tier2_luxury",
    "regent hotels": "tier2_luxury",
    "regent": "tier2_luxury",
    "soho house": "tier2_luxury",
    "soho beach house": "tier2_luxury",
    "beemok": "tier2_luxury",
    "beemok hospitality collection": "tier2_luxury",
    "appellation": "tier2_luxury",
    "faraway": "tier2_luxury",
    "meritage collection": "tier2_luxury",
    "mosaic hotel collection": "tier2_luxury",
    "nomad": "tier2_luxury",
    "mirbeau": "tier2_luxury",
    "mirbeau inn": "tier2_luxury",
    "the goodtime hotel": "tier2_luxury",
    "sh hotels": "tier2_luxury",
    "the standard": "tier2_luxury",
    "registry collection": "tier2_luxury",
    "gran melia": "tier2_luxury",
    "vai": "tier2_luxury",  # VAI Resort Glendale AZ — independent luxury, opens 2026
    # — Luxury all-inclusives (STR 2024 Scale 1)
    "sandals": "tier2_luxury",
    "beaches": "tier2_luxury",
    "beaches resorts": "tier2_luxury",
    "royalton": "tier2_luxury",
    "royalton vessence": "tier2_luxury",
    "hideaway at royalton": "tier2_luxury",
    "moon palace": "tier2_luxury",
    "palace resorts": "tier2_luxury",
    "grand palladium": "tier2_luxury",
    "bahia principe": "tier2_luxury",
    "luxury bahia principe": "tier2_luxury",
    "grand bahia principe": "tier2_luxury",
    "breathless resorts": "tier2_luxury",
    "breathless": "tier2_luxury",
    "dreams resorts": "tier2_luxury",
    "dreams": "tier2_luxury",
    "secrets resorts": "tier2_luxury",
    "secrets": "tier2_luxury",
    "now resorts": "tier2_luxury",
    "now sapphire": "tier2_luxury",
    "now jade": "tier2_luxury",
    "hyatt zilara": "tier2_luxury",
    "hyatt ziva": "tier2_luxury",
    "zilara": "tier2_luxury",
    "ziva": "tier2_luxury",
    "hyatt vivid": "tier2_luxury",
    "hyatt vivid hotels": "tier2_luxury",
    "hyatt vivid hotels & resorts": "tier2_luxury",
    "zoetry wellness resorts": "tier2_luxury",
    "zoetry": "tier2_luxury",
    "iberostar grand collection": "tier2_luxury",
    "iberostar grand": "tier2_luxury",
    "paradisus": "tier2_luxury",
    "excellence resorts": "tier2_luxury",
    "excellence": "tier2_luxury",
    "hotel xcaret": "tier2_luxury",
    "xcaret": "tier2_luxury",
    "unico hotel": "tier2_luxury",
    "unico": "tier2_luxury",
    "impression by secrets": "tier2_luxury",
    "le blanc": "tier2_luxury",
    "live aqua": "tier2_luxury",
    # — Themed luxury / Vegas
    "atlantis": "tier2_luxury",
    "aria resort": "tier2_luxury",
    "aria": "tier2_luxury",
    "aria las vegas": "tier2_luxury",
    "bellagio": "tier2_luxury",
    "the venetian": "tier2_luxury",
    "venetian": "tier2_luxury",
    "palazzo": "tier2_luxury",
    "cosmopolitan las vegas": "tier2_luxury",
    "the cosmopolitan": "tier2_luxury",
    "cosmopolitan of las vegas": "tier2_luxury",
    "cosmopolitan hotel": "tier2_luxury",
    "mgm grand": "tier2_luxury",
    "mgm collection": "tier2_luxury",
    "caesars palace": "tier2_luxury",
    "encore at wynn": "tier2_luxury",
    "encore las vegas": "tier2_luxury",
    "encore boston": "tier2_luxury",
    "w miami": "tier2_luxury",
    "w south beach": "tier2_luxury",
    "w fort lauderdale": "tier2_luxury",
    "w new york": "tier2_luxury",
    "w los angeles": "tier2_luxury",
    "w hollywood": "tier2_luxury",
    "w chicago": "tier2_luxury",
    "w austin": "tier2_luxury",
    # — Caribbean/US luxury independents
    "condado vanderbilt": "tier2_luxury",
    "eau palm beach": "tier2_luxury",
    "eden roc": "tier2_luxury",
    "faena miami": "tier2_luxury",
    "shore club": "tier2_luxury",
    "the shore club": "tier2_luxury",
    "hodges bay": "tier2_luxury",
    "white elephant": "tier2_luxury",
    "nikki beach": "tier2_luxury",
    "nikki beach resort": "tier2_luxury",
    "salamander": "tier2_luxury",
    "salamander resort": "tier2_luxury",
    "the raleigh": "tier2_luxury",
    "the cliff hotel": "tier2_luxury",
    "cobblers cove": "tier2_luxury",
    "the crane": "tier2_luxury",
    "tamarind": "tier2_luxury",
    "the house barbados": "tier2_luxury",
    "le barthelemy": "tier2_luxury",
    "hotel le toiny": "tier2_luxury",
    "hotel saint-barth isle de france": "tier2_luxury",
    "opal collection": "tier2_luxury",
    "trailborn": "tier2_luxury",
    "el san juan hotel": "tier2_luxury",
    "la concha": "tier2_luxury",
    "only you hotels": "tier2_luxury",
    # ============ TIER 3 UPPER UPSCALE ============
    "marriott": "tier3_upper_upscale",
    "marriott hotels": "tier3_upper_upscale",
    "marriott hotel": "tier3_upper_upscale",
    "marriott marquis": "tier3_upper_upscale",
    "hilton": "tier3_upper_upscale",
    "hilton hotels": "tier3_upper_upscale",
    "hilton hotel": "tier3_upper_upscale",
    "hilton hotels and resorts": "tier3_upper_upscale",
    "hilton resort": "tier3_upper_upscale",
    "sheraton": "tier3_upper_upscale",
    "sheraton grand": "tier3_upper_upscale",
    "westin": "tier3_upper_upscale",
    "hyatt regency": "tier3_upper_upscale",
    "hyatt centric": "tier3_upper_upscale",
    "hyatt hotels": "tier3_upper_upscale",
    "le meridien": "tier3_upper_upscale",
    "renaissance hotels": "tier3_upper_upscale",
    "renaissance": "tier3_upper_upscale",
    "autograph collection": "tier3_upper_upscale",
    "tribute portfolio": "tier3_upper_upscale",
    "curio collection by hilton": "tier3_upper_upscale",
    "curio collection": "tier3_upper_upscale",
    "curio": "tier3_upper_upscale",
    "canopy by hilton": "tier3_upper_upscale",
    "canopy": "tier3_upper_upscale",
    "hotel indigo": "tier3_upper_upscale",
    "embassy suites by hilton": "tier3_upper_upscale",
    "embassy suites": "tier3_upper_upscale",
    "hard rock hotel": "tier3_upper_upscale",
    "hard rock": "tier3_upper_upscale",
    "loews": "tier3_upper_upscale",
    "kimpton": "tier3_upper_upscale",
    "omni": "tier3_upper_upscale",
    "gaylord": "tier3_upper_upscale",
    "wyndham grand": "tier3_upper_upscale",
    "mgallery": "tier3_upper_upscale",
    "pullman": "tier3_upper_upscale",
    "movenpick": "tier3_upper_upscale",
    "swissotel": "tier3_upper_upscale",
    "hoxton": "tier3_upper_upscale",
    "the hoxton": "tier3_upper_upscale",
    "ace hotel": "tier3_upper_upscale",
    "graduate hotels": "tier3_upper_upscale",
    "graduate": "tier3_upper_upscale",
    "25hours": "tier3_upper_upscale",
    "outrigger": "tier3_upper_upscale",
    "caribe hilton": "tier3_upper_upscale",
    "destination by hyatt": "tier3_upper_upscale",
    "destination hotels": "tier3_upper_upscale",
    "jdv by hyatt": "tier3_upper_upscale",
    "bunkhouse": "tier3_upper_upscale",
    "unscripted by hyatt": "tier3_upper_upscale",
    "unscripted": "tier3_upper_upscale",
    "dream hotel": "tier3_upper_upscale",
    "tapestry collection": "tier3_upper_upscale",
    "tapestry collection by hilton": "tier3_upper_upscale",
    "tapestry": "tier3_upper_upscale",
    "hilton tapestry collection": "tier3_upper_upscale",
    "archer hotel": "tier3_upper_upscale",
    "warwick": "tier3_upper_upscale",
    "dolce": "tier3_upper_upscale",
    "couples resort": "tier3_upper_upscale",
    "disney": "tier3_upper_upscale",
    "disney hotel": "tier3_upper_upscale",
    "disney lodge": "tier3_upper_upscale",
    "disney resort": "tier3_upper_upscale",
    "disney lakeshore": "tier3_upper_upscale",
    "disney grand floridian": "tier3_upper_upscale",
    "disney riviera": "tier3_upper_upscale",
    "disney contemporary": "tier3_upper_upscale",
    "disney polynesian": "tier3_upper_upscale",
    "disney animal kingdom lodge": "tier3_upper_upscale",
    "disney wilderness lodge": "tier3_upper_upscale",
    "disney yacht club": "tier3_upper_upscale",
    "disney beach club": "tier3_upper_upscale",
    "disney boardwalk": "tier3_upper_upscale",
    "disney coronado springs": "tier3_upper_upscale",
    "gran destino": "tier3_upper_upscale",
    "the ned": "tier3_upper_upscale",
    "recess": "tier3_upper_upscale",
    "postcard cabins": "tier3_upper_upscale",
    "life house": "tier3_upper_upscale",
    "magnolia": "tier3_upper_upscale",
    "magnolia hotel": "tier3_upper_upscale",
    "nh collection": "tier3_upper_upscale",
    "mint house": "tier3_upper_upscale",
    "pan pacific": "tier3_upper_upscale",
    "disney deluxe resorts": "tier3_upper_upscale",
    "club quarters": "tier3_upper_upscale",
    "rosen shingle creek": "tier3_upper_upscale",
    "grand beach": "tier3_upper_upscale",
    "margaritaville": "tier3_upper_upscale",  # STR 2023 confirmed Upper Upscale
    # ============ TIER 4 UPSCALE ============
    "ac hotels": "tier4_upscale",
    "ac hotel": "tier4_upscale",
    "aloft": "tier4_upscale",
    "courtyard": "tier4_upscale",
    "hilton garden inn": "tier4_upscale",
    "hyatt place": "tier4_upscale",
    "hyatt house": "tier4_upscale",
    "four points": "tier4_upscale",
    "element": "tier4_upscale",
    "residence inn": "tier4_upscale",
    "springhill suites": "tier4_upscale",
    "springhill": "tier4_upscale",
    "home2": "tier4_upscale",
    "home2 suites": "tier4_upscale",
    "homewood suites": "tier4_upscale",
    "homewood": "tier4_upscale",
    "moxy": "tier4_upscale",
    "holiday inn": "tier4_upscale",
    "caption by hyatt": "tier4_upscale",
    "motto by hilton": "tier4_upscale",
    "motto": "tier4_upscale",
    "spark by hilton": "tier4_upscale",
    "tempo by hilton": "tier4_upscale",
    "tempo": "tier4_upscale",
    "mercure": "tier4_upscale",
    "novotel": "tier4_upscale",
    "garner": "tier4_upscale",
    "garner hotels": "tier4_upscale",
    "planet hollywood": "tier4_upscale",
    "generations": "tier4_upscale",
    "crowne plaza": "tier4_upscale",
    "doubletree": "tier4_upscale",
    "doubletree by hilton": "tier4_upscale",
    "delta hotels": "tier4_upscale",
    "delta hotel": "tier4_upscale",
    "citizenm": "tier4_upscale",
    "cambria": "tier4_upscale",
    "cambria hotels": "tier4_upscale",
    "voco": "tier4_upscale",
    "even hotels": "tier4_upscale",
    "compass by margaritaville": "tier4_upscale",
    "club med": "tier4_upscale",
    "iberostar": "tier4_upscale",
    "karisma": "tier4_upscale",
    "barcelo": "tier4_upscale",
    "catalonia": "tier4_upscale",
    "divi resorts": "tier4_upscale",
    "divi": "tier4_upscale",
    "el cid resort": "tier4_upscale",
    "fiesta americana": "tier4_upscale",
    "garza blanca": "tier4_upscale",
    "lopesan": "tier4_upscale",
    "occidental": "tier4_upscale",
    "playa hotels": "tier4_upscale",
    "playa resorts": "tier4_upscale",
    "princess hotel": "tier4_upscale",
    "princess grand": "tier4_upscale",
    "princess senses": "tier4_upscale",
    "riu palace": "tier4_upscale",
    "riu": "tier4_upscale",
    "valentin imperial": "tier4_upscale",
    "sunscape resorts": "tier4_upscale",
    "sunscape": "tier4_upscale",
    "temptation resort": "tier4_upscale",
    "nickelodeon resort": "tier4_upscale",
    "azul beach": "tier4_upscale",
    "el dorado": "tier4_upscale",
    "sonesta": "tier4_upscale",
    "sonesta hotel": "tier4_upscale",
    "radisson": "tier4_upscale",
    "under canvas": "tier4_upscale",
    "outbound hotels": "tier4_upscale",
    "outbound": "tier4_upscale",
    "sonder": "tier4_upscale",
    # ============ TIER 5 SKIP ============
    "hampton": "tier5_skip",
    "hampton inn": "tier5_skip",
    "holiday inn express": "tier5_skip",
    "fairfield": "tier5_skip",
    "fairfield inn": "tier5_skip",
    "la quinta": "tier5_skip",
    "wingate": "tier5_skip",
    "comfort inn": "tier5_skip",
    "comfort suites": "tier5_skip",
    "country inn": "tier5_skip",
    "country inn & suites": "tier5_skip",
    "baymont": "tier5_skip",
    "baymont inn": "tier5_skip",
    "drury": "tier5_skip",
    "mainstay": "tier5_skip",
    "mainstay suites": "tier5_skip",
    "sleep inn": "tier5_skip",
    "quality inn": "tier5_skip",
    "best western": "tier5_skip",
    "best western premier": "tier5_skip",
    "clarion": "tier5_skip",
    "candlewood": "tier5_skip",
    "candlewood suites": "tier5_skip",
    "staybridge": "tier5_skip",
    "towneplace": "tier5_skip",
    "towneplace suites": "tier5_skip",
    "wyndham hotel": "tier5_skip",
    "wyndham hotels": "tier5_skip",
    "wyndham garden": "tier5_skip",
    "ramada": "tier5_skip",
    "hawthorn": "tier5_skip",
    "microtel": "tier5_skip",
    "tryp": "tier5_skip",
    "tru": "tier5_skip",
    "tru by hilton": "tier5_skip",
    "everhome": "tier5_skip",
    "everhome suites": "tier5_skip",
    "protea": "tier5_skip",
    "series by marriott": "tier5_skip",
    "studiores": "tier5_skip",
    "four points by sheraton": "tier5_skip",
    "extended stay": "tier5_skip",
    "extended stay america": "tier5_skip",
    "woodspring": "tier5_skip",
    "woodspring suites": "tier5_skip",
    "home inn": "tier5_skip",
    "livaway": "tier5_skip",
    "livaway suites": "tier5_skip",
    "livsmart": "tier5_skip",
    "urcove": "tier5_skip",
    "atwell suites": "tier5_skip",
    "avid hotels": "tier5_skip",
    "aviator suites": "tier5_skip",
    "aspen suites": "tier5_skip",
    "days inn": "tier5_skip",
    "motel 6": "tier5_skip",
    "super 8": "tier5_skip",
    "econo lodge": "tier5_skip",
    "red roof": "tier5_skip",
    "red roof inn": "tier5_skip",
    "red lion": "tier5_skip",
    "rodeway": "tier5_skip",
    "rodeway inn": "tier5_skip",
    "travelodge": "tier5_skip",
    "americinn": "tier5_skip",
    "americas best": "tier5_skip",
    "americas best value": "tier5_skip",
    "park inn": "tier5_skip",
    "glo": "tier5_skip",
    "my place": "tier5_skip",
    "my place hotel": "tier5_skip",
    "sojourn suites": "tier5_skip",
    "howard johnson": "tier5_skip",
    "knights inn": "tier5_skip",
    "budget inn": "tier5_skip",
    "villager": "tier5_skip",
    "budget host": "tier5_skip",
    "scottish inns": "tier5_skip",
    "americas best inn": "tier5_skip",
    "select inn": "tier5_skip",
    "value place": "tier5_skip",
    "budget suites": "tier5_skip",
    "suburban": "tier5_skip",
    "studio 6": "tier5_skip",
    "magnuson": "tier5_skip",
    "ibis": "tier5_skip",
    "ibis budget": "tier5_skip",
    "ibis styles": "tier5_skip",
    "adagio": "tier5_skip",
    "greet": "tier5_skip",
    "jo&joe": "tier5_skip",
    "dazzler": "tier5_skip",
    "dazzler select": "tier5_skip",
    "apartment collection": "tier5_skip",
    "apartment collection by hilton": "tier5_skip",
    "city express": "tier5_skip",
    "disney all-star": "tier5_skip",
    "disney all star": "tier5_skip",
    "disney pop century": "tier5_skip",
    "disney art of animation": "tier5_skip",
    "disney caribbean beach": "tier5_skip",
    "disney port orleans": "tier5_skip",
    "disney movie": "tier5_skip",
    "disney music": "tier5_skip",
    "disney sports": "tier5_skip",
    "universal studios": "tier5_skip",
}


# ═══════════════════════════════════════════════════════════════════════
# PUBLIC API
# ═══════════════════════════════════════════════════════════════════════

VALID_TIERS = (
    "tier1_ultra_luxury",
    "tier2_luxury",
    "tier3_upper_upscale",
    "tier4_upscale",
    "tier5_skip",
)


def get_canonical_tier(brand_name: str) -> Optional[str]:
    """Look up canonical tier for a brand name (case-insensitive)."""
    if not brand_name:
        return None
    return CANONICAL_TIERS.get(brand_name.lower().strip())


def brands_at_tier(tier: str) -> list[str]:
    """Return all canonical brand names at the given tier, alphabetically."""
    return sorted(b for b, t in CANONICAL_TIERS.items() if t == tier)


# Pre-computed tier lists — imported by scorer.py to replace its hardcoded lists
TIER1_ULTRA_LUXURY: list[str] = brands_at_tier("tier1_ultra_luxury")
TIER2_LUXURY: list[str] = brands_at_tier("tier2_luxury")
TIER3_UPPER_UPSCALE: list[str] = brands_at_tier("tier3_upper_upscale")
TIER4_UPSCALE: list[str] = brands_at_tier("tier4_upscale")
TIER5_SKIP: list[str] = brands_at_tier("tier5_skip")


def build_tier_rules_prompt_block() -> str:
    """
    Generate the TIER RULES block for Smart Fill's Gemini extraction prompt.
    Lists representative brands per tier (not every brand, to keep prompt compact).
    """
    tier1_exemplars = [
        "Aman",
        "Four Seasons",
        "Ritz-Carlton",
        "Rosewood",
        "Mandarin Oriental",
        "Peninsula",
        "St. Regis",
        "Waldorf Astoria",
        "Park Hyatt",
        "Montage",
        "Belmond",
        "Auberge",
        "Capella",
        "Raffles",
        "Six Senses",
        "Bulgari",
        "Cheval Blanc",
        "Dorchester",
        "Oetker",
        "LXR",
        "Ritz-Carlton Reserve",
        "Armani",
        "Oberoi",
        "One&Only",
    ]
    tier2_exemplars = [
        "JW Marriott",
        "W Hotels",
        "Edition",
        "Conrad",
        "Fairmont",
        "Sofitel",
        "InterContinental",
        "Grand Hyatt",
        "Andaz",
        "Alila",
        "Thompson",
        "Langham",
        "Viceroy",
        "1 Hotels",
        "Miraval",
        "Pendry",
        "Nobu",
        "SLS",
        "Mondrian",
        "Delano",
        "Banyan Tree",
        "Signia by Hilton",
        "Vignette Collection",
        "Virgin Hotels",
        "Sandals",
        "Royalton",
        "Breathless",
        "Dreams",
        "Secrets",
        "Now Resorts",
        "Hyatt Zilara",
        "Hyatt Ziva",
        "Palace Resorts",
        "Moon Palace",
        "Grand Palladium",
        "Zoetry",
        "Iberostar Grand",
        "Paradisus",
        "Excellence Resorts",
    ]
    tier3_exemplars = [
        "Marriott",
        "Hilton",
        "Sheraton",
        "Westin",
        "Hyatt Regency",
        "Hyatt Centric",
        "Le Meridien",
        "Renaissance",
        "Autograph Collection",
        "Tribute Portfolio",
        "Curio Collection",
        "Canopy",
        "Hotel Indigo",
        "Hard Rock",
        "Loews",
        "Kimpton",
        "Omni",
        "Gaylord",
        "Wyndham Grand",
        "MGallery",
        "Pullman",
        "Swissotel",
        "Embassy Suites",
        "Margaritaville",
        "Ace Hotel",
        "The Hoxton",
        "Disney Deluxe",
    ]
    tier4_exemplars = [
        "Courtyard",
        "AC Hotels",
        "Aloft",
        "Hilton Garden Inn",
        "Hyatt Place",
        "Hyatt House",
        "Four Points",
        "Element",
        "Residence Inn",
        "SpringHill Suites",
        "Home2",
        "Homewood Suites",
        "Moxy",
        "Holiday Inn",
        "Crowne Plaza",
        "DoubleTree",
        "Delta Hotels",
        "citizenM",
        "Novotel",
        "Mercure",
        "Club Med",
        "RIU",
        "Iberostar",
        "Barcelo",
        "Karisma",
    ]
    tier5_exemplars = [
        "Hampton Inn",
        "Holiday Inn Express",
        "Fairfield Inn",
        "La Quinta",
        "Comfort Inn",
        "Days Inn",
        "Motel 6",
        "Super 8",
        "Best Western",
    ]

    return (
        "TIER RULES (STR 2024 Chain Scale + CBRE luxury split):\n"
        f"  tier1_ultra_luxury: {', '.join(tier1_exemplars)}\n"
        f"  tier2_luxury: {', '.join(tier2_exemplars)}\n"
        f"  tier3_upper_upscale: {', '.join(tier3_exemplars)}\n"
        f"  tier4_upscale: {', '.join(tier4_exemplars)}\n"
        f"  tier5_skip (DO NOT assign — budget/midscale excluded from JA pipeline): "
        f"{', '.join(tier5_exemplars)}\n"
        "\n"
        "Guidance for ambiguous cases:\n"
        "  - All-inclusive brands (Sandals, Royalton, Dreams, Secrets,\n"
        "    Hyatt Zilara/Ziva, Palace, Grand Palladium, Moon Palace) =\n"
        "    tier2_luxury per STR Luxury classification.\n"
        "  - Lifestyle boutique (Kimpton, Autograph, Tribute, Curio, Canopy)\n"
        "    = tier3_upper_upscale per STR.\n"
        "  - Select-service (Courtyard, Aloft, Hyatt Place, HGI, Residence Inn,\n"
        "    Crowne Plaza, DoubleTree, Delta Hotels, citizenM) = tier4_upscale\n"
        "    per STR 2023/2024 Chain Scale.\n"
    )


if __name__ == "__main__":
    counts = Counter(CANONICAL_TIERS.values())
    print(f"Total canonical entries: {len(CANONICAL_TIERS)}")
    print()
    for tier in VALID_TIERS:
        print(f"  {tier:<25} {counts.get(tier, 0):>4} entries")
    print()
    invalid = [b for b, t in CANONICAL_TIERS.items() if t not in VALID_TIERS]
    if invalid:
        print(f"  ❌ {len(invalid)} entries with invalid tier: {invalid}")
    else:
        print("  ✅ All tier values are valid")
