"""vendor_seeds.py -- GENERATED by import_vendor_list.py. Do not edit by hand.
Re-run the importer after VENDOR_LIST.xlsx changes.

Source rows: 401  |  name seeds: 159  |  domain seeds: 119
"""

VENDOR_NAME_SEEDS = {
    "4imprint",
    "a career apparel",
    "a universal fire equipment",
    "ad products bazaar",
    "adar medical uniforms",
    "advance service",
    "ahead",
    "alessa wholesale",
    "alphabroder",
    "american seashore",
    "anchor uniforms",
    "atlas levy sewing machine",
    "augusta sportswear",
    "badger sportswear",
    "bandanna",
    "bayly",
    "berne apparel",
    "blue generation",
    "bows n ties",
    "brook taverner",
    "buttonology",
    "calita s tailor desing alteration",
    "careismatic brands",
    "carr textile",
    "cawley",
    "charles river apparel",
    "chef works",
    "clement design",
    "cobmex",
    "collars",
    "cruz label",
    "cutter buck",
    "d zinman textiles ltee",
    "daystar",
    "daytona trimming",
    "digital river",
    "domenica",
    "dorfman milano",
    "e c c associates",
    "east coast umbrella",
    "edwards garment",
    "eiseman ludmar",
    "elegancia tropical genuine panama hats",
    "embroservice",
    "emmaline bags",
    "erb safety",
    "excel labels plus",
    "exclamarketing",
    "fabian couture",
    "fabric base",
    "fashion biz",
    "first class uniforms",
    "footwear specialties",
    "game apparel",
    "game sportswear",
    "goldstar tool",
    "grip flex",
    "hamburger woolen",
    "happy chef",
    "harodite industries",
    "heat express",
    "helly hansen us",
    "henry segal",
    "hero s pride",
    "hirsch solutions",
    "hk hisoa limited",
    "huafang",
    "huzhou ruibang glove",
    "id identity",
    "interpad manufacturing",
    "intuit",
    "j a uniforms",
    "j d sewing",
    "j f promotions",
    "j r embroidery",
    "jaazer apparel",
    "jazun embroidery",
    "jiangsu pinytex textile dyeing finishing",
    "karlowsky",
    "kati sportcap bag",
    "kufner textile",
    "kutesmart qingdao",
    "lafayette",
    "landau",
    "lectra systems",
    "liberty uniforms",
    "locknane",
    "luna smart sewing",
    "mabim suppliers",
    "madeira",
    "midway cap",
    "miro industrial equipment",
    "natural collection",
    "naumd",
    "occunomix",
    "ogs technologies",
    "omni apparel",
    "oriole textile",
    "paragon",
    "peak premium",
    "philips uniform",
    "pinnacle textile",
    "portwest",
    "prenusac",
    "propper sales",
    "radians",
    "ralawise",
    "rapid creative solutions",
    "reflective apparel factory",
    "richard tie fabrics",
    "richpeace",
    "robert kaufman",
    "rosa fabrics",
    "rothco",
    "s s activewear",
    "samuel broome",
    "sanmar",
    "scott notions",
    "sew lit decorators",
    "shanghai china confucian",
    "shindo",
    "shoes for crews",
    "shutter brothers",
    "sidogras s a",
    "simon jersey",
    "stahls",
    "stormtech",
    "subli",
    "superior uniform",
    "surewerx",
    "tenda industry qingdao hengda",
    "textile",
    "textiles south",
    "tie bar",
    "timeless trims",
    "tingley rubber",
    "tootal filtex",
    "transfer express",
    "tri mountain",
    "tsf sportswear",
    "uline",
    "uncommon chef",
    "uniforms unlimited",
    "uniqlo",
    "united thread",
    "universal sewing",
    "vantage apparel",
    "watermen",
    "watkins pr",
    "wawak",
    "wet effect",
    "white swan brands",
    "wilhelmina",
    "wolfmark neckwear",
    "workwear outfitters",
    "xavier dominicis",
    "xor miami",
    "yarrington mills",
    "zhong yuan trading",
}

VENDOR_DOMAIN_SEEDS = {
    "4imprint.com",  # 4IMPRINT
    "adarmedicaluniforms.com",  # ADAR MEDICAL UNIFORMS,LLC
    "aheadhq.com",  # AHEAD LLC
    "alphabroder.com",  # ALPHABRODER
    "anchoruniform.com",  # ANCHOR UNIFORMS
    "apluseveryday.com",  # A+ CAREER APPAREL
    "atlaslevy.com",  # ATLAS LEVY SEWING MACHINE
    "augustasportswear.com",  # AUGUSTA SPORTSWEAR
    "auniversalfire.com",  # A UNIVERSAL FIRE EQUIPMENT, INC
    "baylyinc.com",  # BAYLY,INC
    "bazaarline.com",  # AD PRODUCTS BAZAAR
    "berneapparel.com",  # BERNE APPAREL
    "bluegeneration.com",  # BLUE GENERATION_CIT
    "bows-n-ties.com",  # BOWS-N-TIES
    "brooktaverner.com",  # BROOK TAVERNER
    "carrtextile.com",  # CARR TEXTILE CORPORATION
    "centuryplaceapparel.com",  # PARAGON
    "charlesriverapparel.com",  # CHARLES RIVER APPAREL
    "chefworks.com",  # CHEF WORKS, INC
    "clementdesignusa.com",  # CLEMENT DESIGN USA
    "cobmex.com",  # COBMEX
    "collarsandco.com",  # COLLARS & CO
    "cruzlabel.com",  # CRUZ LABEL
    "cutterbuck.com",  # CUTTER & BUCK
    "daystarapparel.com",  # DAYSTAR
    "digitalriver.com",  # DIGITAL RIVER
    "dominicis.com",  # XAVIER DOMINICIS
    "dorfman-pacific.com",  # DORFMAN MILANO
    "e-erb.com",  # ERB SAFETY INTERNATIONAL
    "eastcoastumbrella.com",  # EAST COAST UMBRELLA
    "edwardsgarment.com",  # EDWARDS GARMENT CORP.
    "eleganciatropical.com",  # ELEGANCIA TROPICAL GENUINE PANAMA HATS
    "embroservice.com",  # EMBROSERVICE
    "empirecollectionagency.com",  # E.C.C & ASSOCIATES
    "encompassgroup.net",  # WHITE SWAN BRANDS
    "excellabelsplus.com",  # EXCEL LABELS PLUS
    "exclamarketing.com",  # EXCLAMARKETING
    "executiveapparel.com",  # FCG LLC
    "fabiancouture.com",  # FABIAN COUTURE GROUP
    "fabricbaseinc.com",  # FABRIC BASE, INC.
    "fashionbiz.ca",  # FASHION BIZ
    "fcuniforms.com",  # FIRST CLASS UNIFORMS
    "filtexintl.com",  # TOOTAL-FILTEX INTERNATIONAL
    "footwearspecialties.com",  # FOOTWEAR SPECIALTIES INTERNATIONAL
    "foundersportgroup.com",  # BADGER SPORTSWEAR
    "gadolcisa.com",  # ADVANCE SERVICE CORP.
    "game-apparel.com",  # GAME APPAREL
    "gamesportswear.com",  # GAME SPORTSWEAR
    "goldstartool.com",  # GOLDSTAR TOOL
    "gripflexcorporation.com",  # GRIP-FLEX CORPORATION
    "happychefuniforms.com",  # HAPPY CHEF
    "harodite.com",  # HARODITE INDUSTRIES INC
    "heatexpressmiami.com",  # HEAT EXPRESS, INC.
    "herospride.com",  # HERO'S PRIDE
    "hic.us",  # HIRSCH SOLUTIONS LLC
    "interpads.com",  # INTERPAD MANUFACTURING
    "intuit.com",  # INTUIT
    "katisportcap.com",  # KATI SPORTCAP & BAG
    "kiteflag.com",  # J & F PROMOTIONS LTD
    "kufner.com",  # KUFNER TEXTILE CORPORATION
    "lafayette.com",  # LAFAYETTE USA CORP.
    "landau.com",  # LANDAU
    "lectra.com",  # LECTRA SYSTEMS,INC.
    "libertyuniform.com",  # LIBERTY UNIFORMS
    "linousa.com",  # NATURAL COLLECTION CORP
    "locknane.com",  # LOCKNANE, INC.
    "mabiminc.com",  # MABIM INTERNATIONAL SUPPLIERS INC.
    "madeirausa.com",  # MADEIRA USA
    "mail.uniqlo-usa.com",  # UNIQLO
    "miroindustrialequipment.com",  # MIRO INDUSTRIAL EQUIPMENT
    "ms16.hinet.net",  # JAZUN EMBROIDERY
    "naumd.com",  # NAUMD
    "occunomix.com",  # OCCUNOMIX
    "ogstech.com",  # OGS TECHNOLOGIES, INC
    "omniapparatech.com",  # OMNI APPAREL INC.
    "ottocap.com",  # OTTO INTERNATIONAL
    "peakpremium.com",  # PEAK PREMIUM
    "philipsuniform.com",  # PHILIPS UNIFORM MFG
    "pinnacletextile.com",  # PINNACLE TEXTILE
    "propper.com",  # PROPPER INTERNATIONAL SALES
    "pvh.com",  # PVH
    "radians.com",  # RADIANS, INC.
    "ralawise.com",  # RALAWISE
    "rapidcs.in",  # RAPID CREATIVE SOLUTIONS
    "reflectiveapparel.com",  # REFLECTIVE APPAREL FACTORY
    "robertkaufman.com",  # ROBERT KAUFMAN
    "rtfabrics.com",  # RICHARD TIE FABRICS
    "sanmar.com",  # SANMAR
    "sbroome.com",  # SAMUEL BROOME
    "scottnotions.com",  # SCOTT NOTIONS, INC
    "shopelc.com",  # EISEMAN-LUDMAR
    "shutterbrothersllc.com",  # SHUTTER BROTHERS LLC
    "sidogras.com",  # SIDOGRAS, S.A.
    "ssactivewear.com",  # S&S ACTIVEWEAR LLC.
    "stahls.com",  # STAHLS' INC
    "stormtechusa.com",  # STORMTECH USA INC
    "superioruniformgroup.com",  # SUPERIOR UNIFORM GROUP
    "surewerx.com",  # SUREWERX USA INC
    "textileusa.net",  # TEXTILE USA
    "thecawleyco.com",  # CAWLEY COMPANY
    "timelesstrims.com",  # TIMELESS TRIMS
    "tingleyrubber.com",  # TINGLEY RUBBER CORP.
    "transferexpress.com",  # TRANSFER EXPRESS
    "trimountain.com",  # TRI-MOUNTAIN
    "tsfsportswear.com",  # TSF SPORTSWEAR
    "uline.com",  # ULINE
    "uncommonchefcollection.com",  # UNCOMMON CHEF
    "unisew.com",  # UNIVERSAL SEWING
    "unitedthread.us",  # UNITED THREAD
    "vantageapparel.com",  # VANTAGE APPAREL
    "watermenbrand.com",  # WATERMEN
    "watkinspr.com",  # WATKINS PR
    "wawak.com",  # WAWAK
    "weteffect.com",  # WET EFFECT
    "wilhelmina.com",  # WILHELMINA
    "wolfmarkties.com",  # WOLFMARK NECKWEAR
    "wwof.com",  # WORKWEAR OUTFITTERS LLC
    "xormiami.com",  # XOR MIAMI LLC
    "yarinngtonmills.com",  # YARRINGTON MILLS CORP
}
