"""Agent 5 — Scheduler (v2).

What changed from v1:
  - Send timing scales with timeline_label (URGENT goes out tomorrow,
    COOL waits a week — v1 used flat send delays based only on fit_score)
  - Send time is Tue-Thu 9-11 AM (industry data says best response rates)
  - Returns FULL touch objects with subject + body draft, not just
    placeholder date strings
  - Existing clients get a different sequence (no "breakup" email —
    they're already a customer; touch 3 is a fresh value-prop instead)
  - Pure Python — no LLM call (deterministic timing logic). The actual
    follow-up email content is generated on demand via the existing
    /sequence/{id} endpoint, which now uses richer context.
"""

from __future__ import annotations

import logging
from datetime import datetime, timedelta

from .state import PitchState

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# Send time calculation
# ─────────────────────────────────────────────────────────────────────────────


def _next_business_morning(start: datetime, days_offset: int) -> datetime:
    """Find the next Tue-Thu morning (9 AM) at least `days_offset` days
    from `start`. Mon/Fri/weekends get pushed forward to Tuesday."""
    target = start + timedelta(days=days_offset)
    target = target.replace(hour=9, minute=0, second=0, microsecond=0)

    # weekday(): Mon=0, Tue=1, Wed=2, Thu=3, Fri=4, Sat=5, Sun=6
    weekday = target.weekday()
    if weekday == 0:  # Monday → Tuesday
        target += timedelta(days=1)
    elif weekday >= 4:  # Fri/Sat/Sun → Tuesday
        target += timedelta(days=(8 - weekday) % 7 or 7)
        # Re-snap to next Tuesday safely
        while target.weekday() != 1:
            target += timedelta(days=1)
    return target


def _send_offset_days(
    timeline_label: str | None, fit_score: int, is_client: bool
) -> int:
    """How many days after now should the first email go out?

    Existing clients: tomorrow (relationship already exists, no warmup needed).
    URGENT: tomorrow (they need uniforms in 3-6mo, every day matters).
    HOT: 2 days (sweet spot — slight delay shows it's not blast outreach).
    WARM: 4 days (no rush).
    COOL: 7 days (very long lead time anyway).
    """
    if is_client:
        return 1
    label = (timeline_label or "").upper()
    if label == "URGENT":
        return 1
    if label == "HOT":
        return 2
    if label == "WARM":
        return 4
    if label == "COOL":
        return 7
    # TBD / unknown → use fit_score
    if fit_score >= 80:
        return 1
    if fit_score >= 50:
        return 3
    return 5


# ─────────────────────────────────────────────────────────────────────────────
# Follow-up sequence design
# ─────────────────────────────────────────────────────────────────────────────


def _design_followups(
    send_time: datetime,
    fit_score: int,
    timeline_label: str | None,
    is_client: bool,
    contact_first_name: str,
    hotel_name: str,
) -> list[dict]:
    """Return a list of touch objects with day/type/headline/template.

    The actual email body is filled in on demand by /sequence/{id} —
    here we just plan the cadence + label each touch's purpose."""

    if is_client:
        return [
            {
                "day": 0,
                "type": "Initial",
                "headline": "Initial outreach",
                "template": "Use the email already generated by the Writer agent.",
            },
            {
                "day": 5,
                "type": "Value Hook",
                "headline": f"Reference one specific JA service {hotel_name} hasn't tried yet",
                "template": (
                    "Suggest a specific expansion: a department they haven't ordered for yet, "
                    "a recent property addition, or a seasonal reorder window. "
                    "Reference your existing relationship explicitly."
                ),
            },
            {
                "day": 14,
                "type": "Check-in",
                "headline": "Soft check-in (no pitch)",
                "template": (
                    "2-3 line note checking in. No new pitch — just 'thinking of "
                    "you, here if useful'. Maintains relationship without pressure."
                ),
            },
        ]

    # Cold prospect sequences scale with timeline
    label = (timeline_label or "").upper()
    if label in ("URGENT", "HOT") or fit_score >= 80:
        # Tight cadence: 0d / +5d / +12d
        return [
            {
                "day": 0,
                "type": "Initial",
                "headline": "Initial cold outreach",
                "template": "Use the email already generated by the Writer agent.",
            },
            {
                "day": 5,
                "type": "Value Hook",
                "headline": "Lead with a specific value prop tied to their pain",
                "template": (
                    "Reference one of the value props from the Analyst. Tie it to "
                    "a specific pain point found in research. Soft CTA ('would 15 "
                    "minutes next Tuesday or Thursday work?')."
                ),
            },
            {
                "day": 12,
                "type": "Breakup",
                "headline": "Short breakup email — gentle urgency",
                "template": (
                    "3-4 line breakup. Acknowledge timing might not be right, ask "
                    "if there's a better time to reconnect, then back off. The "
                    "'sorry to bother you' tone often gets more responses than "
                    "earlier touches."
                ),
            },
        ]

    if label == "WARM" or 50 <= fit_score < 80:
        # Moderate cadence: 0d / +7d / +18d
        return [
            {
                "day": 0,
                "type": "Initial",
                "headline": "Initial cold outreach",
                "template": "Use the email already generated by the Writer agent.",
            },
            {
                "day": 7,
                "type": "LinkedIn Touch",
                "headline": "Connect on LinkedIn with the message generated",
                "template": (
                    "Send the LinkedIn note generated by the Writer. Multi-channel "
                    "lifts response rates. Don't email them again the same day."
                ),
            },
            {
                "day": 18,
                "type": "Soft Reconnect",
                "headline": "Acknowledge the long lead-time, offer something useful",
                "template": (
                    "Acknowledge their opening is still a year+ out. Share a "
                    "useful resource (case study, sample uniform photo, "
                    "industry benchmark) with NO ask. Builds goodwill for the "
                    "real outreach window in 6-9 months."
                ),
            },
        ]

    # COOL or low fit
    return [
        {
            "day": 0,
            "type": "Initial",
            "headline": "Initial cold outreach (very soft)",
            "template": "Use the email already generated by the Writer agent.",
        },
        {
            "day": 21,
            "type": "Soft Reconnect",
            "headline": "Polite check-in, no pitch",
            "template": (
                "Acknowledge it's still very early. Offer a useful resource "
                "with NO meeting ask. Goal: stay top-of-mind for when they "
                "actually start uniform planning in 12-15 months."
            ),
        },
    ]


# ─────────────────────────────────────────────────────────────────────────────
# Public agent entry
# ─────────────────────────────────────────────────────────────────────────────


def scheduler_agent(state: PitchState) -> PitchState:
    contact_name = state.get("contact_name", "")
    hotel_name = state.get("hotel_name", "")
    fit_score = state.get("fit_score") or 0
    timeline_label = state.get("timeline_label")
    is_client = bool(state.get("is_client"))

    logger.info(
        f"[Scheduler] Planning send + follow-ups for {contact_name} at {hotel_name}"
    )

    # If the email was skipped (low fit) or rejected after max retries,
    # don't bother scheduling
    if not state.get("email_body"):
        logger.info("[Scheduler] No email body — skipping schedule")
        return {
            **state,
            "send_time": "",
            "follow_up_sequence": [],
        }

    now = datetime.now()
    offset = _send_offset_days(timeline_label, fit_score, is_client)
    send_time = _next_business_morning(now, offset)
    send_time_str = send_time.strftime("%A %B %d, %Y at %I:%M %p")

    follow_ups = _design_followups(
        send_time=send_time,
        fit_score=fit_score,
        timeline_label=timeline_label,
        is_client=is_client,
        contact_first_name=(contact_name.split()[0] if contact_name else ""),
        hotel_name=hotel_name,
    )

    # Add concrete dates
    for touch in follow_ups:
        touch_date = send_time + timedelta(days=touch["day"])
        # Snap to Tue-Thu morning
        touch_date = _next_business_morning(touch_date, 0)
        touch["scheduled_for"] = touch_date.strftime("%A %B %d, %Y")

    logger.info(
        f"[Scheduler] Send @ {send_time_str} (offset +{offset}d). "
        f"{len(follow_ups)} follow-up(s) planned."
    )

    return {
        **state,
        "send_time": send_time_str,
        "follow_up_sequence": follow_ups,
    }
